services:
  db:
    image: mysql:5.7
    container_name: participatory-db
    command: --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - default

  webapp:
    build:
      context: .
      dockerfile: docker/config/webapp/Dockerfile
    container_name: participatory-webapp
    expose:
      - 9004
    volumes:
      - .:/var/www/html
      - ./docker/config/webapp/php/ini/limitation.ini:/usr/local/etc/php/conf.d/limitation.ini
      - ./docker/config/webapp/php/ini/security.ini:/usr/local/etc/php/conf.d/security.ini
      - ./docker/config/webapp/php/ini/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./docker/config/webapp/php/ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/config/webapp/php/ini/postal.ini:/usr/local/etc/php/conf.d/postal.ini
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    env_file: .env
    depends_on:
      - db
    networks:
      - default

  nginx:
    image: fphgov/nginx
    container_name: participatory-nginx
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx
      - ./:/var/www/html
      - ./docker/config/cert:/opt/cert
    depends_on:
      - db
      - webapp

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  minio:
    image: bitnami/minio:2022-debian-11
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ~
      MINIO_SECRET_KEY: ~
      MINIO_DEFAULT_BUCKETS: 'private,shared:public'

  dozzle:
    container_name: participatory-dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  libpostal:
    image: fphgov/libpostal:latest
    environment:
      - LISTEN_PORT=9501
    expose:
      - 9501

networks:
  default:
    driver: bridge
