version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: participatory_db
    command: --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: bp-pb
      MYSQL_USER: bp-pb
      MYSQL_PASSWORD: LhNqFKFseu8MB9pW
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - internal

  webapp:
    build:
      context: .
      dockerfile: docker/config/webapp/Dockerfile
    container_name: participatory_webapp
    expose:
      - 9001
    ports:
      - 9001:9001
    volumes:
      - .:/var/www/html
      - ./docker/config/webapp/php/ini/memory.ini:/usr/local/etc/php/conf.d/memory.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      PHP_IDE_CONFIG: 'serverName=webapp'
      XDEBUG_CONFIG: 'remote_enable=1 remote_host=172.2.0.113 remote_port=9001'
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    container_name: participatory_nginx
    networks:
      - internal
    ports:
      - 9080:80
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./docker/data/nginx/logs:/var/log/nginx
      - ./:/var/www/html
    restart: always
    depends_on:
      - db
      - webapp

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

networks:
  internal:
    driver: bridge
